{% set name = "session-info" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/session_info-{{ version }}.tar.gz
  sha256: 3cda5e03cca703f32ae2eadbd6bd80b6c21442cfb60e412c21cb8ad6d5cbb6b7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - stdlib-list

test:
  imports:
    - session_info
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gitlab.com/joelostblom/session_info
  summary: session_info outputs version information for modules loaded in the current session, Python, and the OS.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ivirshup
